[package]
name = "legibility-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
legibility-core = { workspace = true }
legibility-dom = { workspace = true }
legibility-sanitize = { workspace = true }
