[package]
name = "legibility-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "lgb"
path = "src/main.rs"

[dependencies]
legibility = { path = "../legibility" }
legibility-core = { workspace = true }
legibility-dom = { workspace = true }
