//! A generated DOM, rather than generated bytes.
//!
//! `extract_bytes` reaches the parser's error recovery quickly and then mostly stays there: random
//! bytes are almost never a document with a repeated comment template, a nested thread, or a
//! heading that restates a title. Those are the shapes the *engine* has rules about, and a byte
//! fuzzer will not build one by chance in any useful number of runs.
//!
//! So the input is an `Arbitrary` tree, rendered to HTML. libFuzzer then mutates the tree rather
//! than the text, which walks the space of structures instead of the space of syntax errors.
#![no_main]

use arbitrary::Arbitrary;
use legibility_core::Limits;
use libfuzzer_sys::fuzz_target;

/// Elements chosen for what the engine reacts to, not for coverage of HTML.
#[derive(Arbitrary, Debug)]
enum Tag {
    Div,
    Article,
    Main,
    Section,
    P,
    Li,
    Ul,
    A,
    H1,
    H2,
    Time,
    Nav,
    Footer,
    Form,
    Blockquote,
    Pre,
    Custom,
}

impl Tag {
    fn name(&self) -> &'static str {
        match self {
            Tag::Div => "div",
            Tag::Article => "article",
            Tag::Main => "main",
            Tag::Section => "section",
            Tag::P => "p",
            Tag::Li => "li",
            Tag::Ul => "ul",
            Tag::A => "a",
            Tag::H1 => "h1",
            Tag::H2 => "h2",
            Tag::Time => "time",
            Tag::Nav => "nav",
            Tag::Footer => "footer",
            Tag::Form => "form",
            Tag::Blockquote => "blockquote",
            Tag::Pre => "pre",
            Tag::Custom => "my-widget",
        }
    }
}

#[derive(Arbitrary, Debug)]
enum Node {
    Text(String),
    Element {
        tag: Tag,
        class: Option<String>,
        href: bool,
        datetime: bool,
        children: Vec<Node>,
    },
    /// A sibling run of one subtree, which is how every rule about repetition gets reached at all.
    Repeat {
        times: u8,
        item: Box<Node>,
    },
}

fn render(n: &Node, out: &mut String, depth: u8) {
    // Bounded here rather than by the arena's depth cap, so the *generator* cannot spend its whole
    // budget on one chain and never produce breadth.
    if depth > 24 || out.len() > 512 * 1024 {
        return;
    }
    match n {
        Node::Text(s) => {
            for c in s.chars().take(200) {
                match c {
                    '<' => out.push_str("&lt;"),
                    '>' => out.push_str("&gt;"),
                    '&' => out.push_str("&amp;"),
                    _ => out.push(c),
                }
            }
        }
        Node::Element { tag, class, href, datetime, children } => {
            out.push('<');
            out.push_str(tag.name());
            if let Some(c) = class {
                out.push_str(" class=\"");
                for ch in c.chars().take(40).filter(|ch| ch.is_alphanumeric() || *ch == '-') {
                    out.push(ch);
                }
                out.push('"');
            }
            if *href {
                out.push_str(" href=\"/x\"");
            }
            if *datetime {
                out.push_str(" datetime=\"2026-08-05T12:00:00Z\"");
            }
            out.push('>');
            for c in children.iter().take(16) {
                render(c, out, depth + 1);
            }
            out.push_str("</");
            out.push_str(tag.name());
            out.push('>');
        }
        Node::Repeat { times, item } => {
            for _ in 0..(*times % 24) {
                render(item, out, depth + 1);
                if out.len() > 512 * 1024 {
                    return;
                }
            }
        }
    }
}

fuzz_target!(|root: Node| {
    let mut body = String::new();
    render(&root, &mut body, 0);
    let html = format!("<html><head><title>t</title></head><body>{body}</body></html>");

    let limits = Limits::BROWSER;
    let (arena, hit) = legibility_dom::BuildArena::parse_to_arena(&html, limits);
    let out = legibility_core::extract_all(&arena, limits);
    assert!(
        out.selection.article.is_some() || out.selection.no_article.is_some(),
        "extraction produced neither a region nor a reason"
    );

    // The comment accounting invariant plan §1.9 requires: a thread that is short of what the page
    // claims must say it is truncated. Reachable here and essentially nowhere else, because it
    // needs a generated thread with a generated count beside it.
    let c = &out.comments.completeness;
    assert!(
        c.claimed_total.is_none_or(|n| n == c.present) || c.truncated,
        "present {} of a claimed {:?} without reporting truncation",
        c.present,
        c.claimed_total
    );

    let _ = legibility_dom::json::extraction_json_limited(&arena, &out, hit, None, limits);
});
